(() => {
  const data = window.FX_HOMEWORK_REVIEW; if (!data) return;
  const versions = data.reviewVersions || []; let panel; let version; let activeId = null; let observer; let abort; let resizeObserver;
  const getVersion = id => versions.find(item => item.id === id) || versions.find(item => item.default) || versions[0];
  const anchor = id => document.querySelector(`[data-review-anchor="${id}"]`);
  const constrain = () => { if (!panel) return; const left = Math.min(Math.max(12, panel.offsetLeft), Math.max(12, innerWidth - panel.offsetWidth - 12)); const top = Math.min(Math.max(12, panel.offsetTop), Math.max(12, innerHeight - panel.offsetHeight - 12)); panel.style.left = `${left}px`; panel.style.top = `${top}px`; panel.style.right = 'auto'; };
  const clearMarkers = () => document.querySelectorAll('.fx-review-marker').forEach(node => node.remove());
  const renderMarkers = () => { clearMarkers(); if (!panel) return; version.items.forEach((item, index) => { const node = anchor(item.anchorId); if (!node) return; const rect = node.getBoundingClientRect(); if (rect.bottom < 0 || rect.top > innerHeight) return; const marker = document.createElement('button'); marker.className = 'fx-review-marker'; marker.textContent = String(index + 1); marker.style.left = `${Math.min(Math.max(8, rect.left + 10), innerWidth - 36)}px`; marker.style.top = `${Math.min(Math.max(8, rect.top + 10), innerHeight - 36)}px`; marker.title = item.title; marker.onclick = () => focus(item.anchorId); document.body.append(marker); }); };
  const focus = id => { const node = anchor(id); if (!node) return; activeId = id; renderPanel(); node.scrollIntoView({ behavior:'smooth', block:'center' }); document.querySelectorAll('.fx-review-highlight').forEach(item => item.classList.remove('fx-review-highlight')); node.classList.add('fx-review-highlight'); setTimeout(() => node.classList.remove('fx-review-highlight'), 1600); };
  const drag = handle => { let point; handle.onpointerdown = event => { if (event.target.closest('button,select,a')) return; point = { x:event.clientX, y:event.clientY, left:panel.offsetLeft, top:panel.offsetTop }; handle.setPointerCapture(event.pointerId); }; handle.onpointermove = event => { if (!point) return; panel.style.left = `${point.left + event.clientX - point.x}px`; panel.style.top = `${point.top + event.clientY - point.y}px`; panel.style.right = 'auto'; constrain(); }; handle.onpointerup = () => { point = null; }; };
  const renderPanel = () => { if (!panel) return; const source = data.source || {}; panel.innerHTML = `<div class="fx-review-head" data-drag><div class="fx-review-title"><span>过稿范围</span><strong>${data.title}</strong><em>${version.label}</em></div><button class="fx-review-close" data-close aria-label="返回演示模式">×</button></div><div class="fx-review-body"><div class="fx-review-topline"><span>${version.items.length} 项待确认</span>${source.url ? `<a href="${source.url}" target="_blank" rel="noopener">查看石墨产品稿 ↗</a>` : `<span class="is-disabled">石墨产品稿待补充</span>`}</div><div class="fx-review-items">${version.items.map((item, index) => { const available = !!anchor(item.anchorId); return `<article class="fx-review-item ${activeId === item.anchorId ? 'is-active' : ''}"><span class="fx-review-number">${index + 1}</span><div><strong>${item.title}</strong><p>${item.purpose}</p><button data-locate="${item.anchorId}" ${available ? '' : 'disabled'}>${available ? '定位页面' : '当前页面未打开'}</button></div></article>`; }).join('')}</div></div>`; panel.querySelector('[data-close]').onclick = () => window.FX_SET_REVIEW_MODE?.(false); panel.querySelectorAll('[data-locate]').forEach(button => button.onclick = () => focus(button.dataset.locate)); drag(panel.querySelector('[data-drag]')); };
  const refresh = () => { renderPanel(); renderMarkers(); };
  window.FX_SET_REVIEW_VERSION = id => { version = getVersion(id); activeId = null; refresh(); };
  window.FX_EXIT_REVIEW_MODE = () => { abort?.abort(); observer?.disconnect(); resizeObserver?.disconnect(); clearMarkers(); document.querySelectorAll('[data-review-anchor]').forEach(node => node.removeAttribute('data-review-anchor')); panel?.remove(); panel = null; activeId = null; };
  window.FX_START_REVIEW_MODE = () => {
    if (panel) return; version = getVersion(new URLSearchParams(location.search).get('reviewVersion')); abort = new AbortController(); panel = document.createElement('aside'); panel.id = 'fx-review-panel'; document.body.append(panel); refresh(); constrain(); resizeObserver = new ResizeObserver(constrain); resizeObserver.observe(panel);
    addEventListener('scroll', renderMarkers, { capture:true, signal:abort.signal }); addEventListener('resize', () => { constrain(); renderMarkers(); }, { signal:abort.signal });
    let queued = false; observer = new MutationObserver(mutations => { const own = node => node?.nodeType === 1 && (node === panel || panel.contains(node) || node.classList.contains('fx-review-marker')); if (mutations.every(mutation => own(mutation.target) || [...mutation.addedNodes, ...mutation.removedNodes].every(own))) return; if (!queued) { queued = true; requestAnimationFrame(() => { queued = false; refresh(); }); } }); observer.observe(document.body, { childList:true, subtree:true });
  };
  if (new URLSearchParams(location.search).get('review') === '1') window.FX_START_REVIEW_MODE();
})();
